sudo: required

language: node_js
node_js:
  - "5.0.0"

services:
  - docker

install:
  - npm install

script:
  - npm run test:unit
  - npm run lint
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
  - npm run test:integration
