sudo: required

language: node_js
node_js:
  - "5.0.0"

services:
  - docker

install: true

script:
  - npm run test:unit
  - docker-compose up app
  - docker ps -a
  - npm run test:integration
  - npm run lint
