sudo: required

language: node_js
node_js:
  - "5.0.0"

services:
  - docker

install:
  - npm install

script:
  - npm run test:unit
  - npm run lint
  - docker build -t app/app .
  - docker run -d -p 127.0.0.1:3000:3000 app/app
  - docker ps -a
  - npm run test:integration
