app:
  build: .
  ports:
    - "3000:3000"
test:
  image: baseprojectjs_app
  command: npm run test:unit && npm run lint && npm run test:integration 
  environment:
    - SERVER_URL=http://app:3000/
  links:
    - app
